### ISSUE TITLE
EOF occurred in violation of protocol while Pulling pulses

### ISSUE THREAD

**Issue by npormambi** [AlienVault-Labs/OTX-Python-SDK#29]
Hello,

I am using pthon2.7, when I use 
pulses = otx.getall()
It gives below error,
Traceback (most recent call last):
  File "otx.py", line 7, in <module>
    pulses = otx.getall()
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 236, in getall
    json_data = self.get(next_page_url)
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 81, in get
    raise e
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

Anyone is aware of this issue, I tried the same with python3.4 as well still getting same error
Running ubuntu 14.04

Thanks,
Npormambi

**Comment by npormambi** [comment]
@chrisdoman  any update on this.

**Comment by npormambi** [comment]
@chrisdoman  this is something helpful to fix the issue
http://stackoverflow.com/questions/32115607/python-3-4-ssl-error-urlopen-error-eof-occurred-in-violation-of-protocol-ssl-c

**Comment by chrisdoman** [comment]
Thanks npormambi. No update yet but I am looking into it and will update soon.

**Comment by chrisdoman** [comment]
Hi,

 I've ran the SDK on Ubuntu 14.04 with python 2.7 and I'm not getting this error.
 Looking into it, this may be an issue with the OpenSSL library on your machine.

 There are a couple of work arounds you might want to try, though I can't test these to confirm they will work here-
- http://stackoverflow.com/questions/28564455/python-mechanise-urllib2-urlerror-violation-of-protocol-handling-of-https

import ssl
ssl.PROTOCOL_SSLv23 = ssl.PROTOCOL_TLSv1


Thanks,

**Comment by npormambi** [comment]
@chrisdoman  working with python 2.7 and ubuntu 14.04, but still getting the same error.
![screenshot from 2017-03-06 09 13 59](https://cloud.githubusercontent.com/assets/16058609/23613585/07402bfe-024e-11e7-90de-d74063b1894e.png)

**Comment by alaaalii** [comment]
What is the output of `python --version` and `python -c "import ssl; print ssl.OPENSSL_VERSION"`?

**Comment by npormambi** [comment]
@alaaalii please check the required output belo
![screenshot from 2017-03-06 15 35 06](https://cloud.githubusercontent.com/assets/16058609/23628617/d8e7c944-0282-11e7-9474-1e0be090b2e8.png)

**Comment by alaaalii** [comment]
@npormambi run your Python script using `python otx.py` not `python2.7 otx.py`, what do you get? And please paste the output as text, not a screenshot.

**Comment by npormambi** [comment]
@alaaalii thanks a lot it worked :)
do you know whats the exact issue is in this case?
Because I want to work with python 3, how can i avoid this issue?

**Comment by alaaalii** [comment]
@npormambi I don't understand, so you still sometimes get the error when using `python otx.py`? But you always get the error when you run `python2.7 otx.py`? What I suspected is because you might somehow have two versions of Python2.7 installed. Try rerunning the commands I mentioned earlier but using `python2.7`, so `python2.7 --version` and `python2.7 -c "import ssl; print ssl.OPENSSL_VERSION"` and see if it's different than what you sent before.

If this is a machine owned by you, and it is safe to do so, I advise you to also make sure packages in your Ubuntu are up to date by running `sudo apt-get update && sudo apt-get upgrade`. If that doesn't fix it, you could simply just remove all versions of Python and reinstall from scratch.

Otherwise, it will be pretty difficult to track this down here, especially when this is not an issue with the OTX SDK. Good luck.

**Comment by npormambi** [comment]
@alaaalii  Thanks for the update.
Its been week  now, i am not facing any issues.
If i do in future will definitely try solution suggested by you.
Thanks a lot :)

**Comment by wagner-certat** [comment]
Also the output of `alias python2.7` and `which python2.7` would be interesting in comparison with the smae outputs with `python` instead of `python2.7`.

**Comment by npormambi** [comment]
@wagner-certat 
Please find the below outputs 
![otx error](https://cloud.githubusercontent.com/assets/16058609/24556932/9848edf2-1653-11e7-8509-a5f6f9c7de0e.GIF)

**Comment by wagner-certat** [comment]
To get the target of symbolic links you can use `ls -l $(which python)` and `ls -l $(which python2.7)`

You can copy and paste the in/output from the terminal to your comment, use the code-markup.

**Comment by npormambi** [comment]
@wagner-certat 
![image](https://cloud.githubusercontent.com/assets/16058609/24673041/8df5ced0-1994-11e7-9090-5ad2d744c9bc.png)

**Comment by wagner-certat** [comment]
Then both are the same and the assumption by @alaaalii can't be proven.
